<?php
session_start();
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__ . '/db_connect.php';

const MAX_LESSONS_PER_SUBJECT = 3;

function fetchAllRows(PDOStatement $statement): array {
    return $statement->fetchAll(PDO::FETCH_ASSOC) ?: [];
}

function jsonResponse(array $payload, int $statusCode = 200): void {
    http_response_code($statusCode);
    echo json_encode($payload, JSON_UNESCAPED_UNICODE);
    exit;
}

function postValue(string $key, $default = '') {
    return isset($_POST[$key]) ? trim((string) $_POST[$key]) : $default;
}

function ensureLessonDocumentColumns(PDO $conn): void
{
    // Documents are stored as lesson_resources; do not alter the supplied schema.
}

function sanitizePathSegment(string $value, string $fallback = 'unknown'): string
{
    $value = trim($value);
    if ($value === '') {
        return $fallback;
    }

    $value = preg_replace('/[^A-Za-z0-9._-]+/', '_', $value);
    $value = trim((string) $value, "._-");
    return $value !== '' ? $value : $fallback;
}

function generateLessonId(PDO $conn): string
{
    throw new LogicException('lesson_id is generated by public.lessons');
}

function countSubjectLessons(PDO $conn, string $subjectId): int
{
    $stmt = $conn->prepare('SELECT COUNT(*) FROM public.lessons WHERE course_id = :subject_id');
    $stmt->execute([':subject_id' => $subjectId]);
    return (int) $stmt->fetchColumn();
}

function ensureSubjectTeachersTable(PDO $conn): void
{
    // `course_teachers` is already created by database-v2.sql.
}

function buildLessonMediaSegments(string $teacherId, string $subjectId, string $lessonId, string $mediaType): array
{
    return [
        'teachers',
        sanitizePathSegment($teacherId, 'unassigned'),
        'subjects',
        sanitizePathSegment($subjectId, 'subject'),
        'lessons',
        sanitizePathSegment($lessonId, 'lesson'),
        sanitizePathSegment($mediaType, 'files'),
    ];
}

function buildVideoMediaSegments(string $teacherId, string $subjectId): array
{
    return [
        'teachers',
        sanitizePathSegment($teacherId, 'unassigned'),
        'subjects',
        sanitizePathSegment($subjectId, 'subject'),
        'videos',
    ];
}

function uploadLessonFile(string $fieldName, array $segments, string $prefix): array
{
    if (!isset($_FILES[$fieldName]) || !is_array($_FILES[$fieldName])) {
        return ['path' => '', 'name' => ''];
    }

    $file = $_FILES[$fieldName];
    if ((int) ($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
        return ['path' => '', 'name' => ''];
    }

    $relativeDir = 'uploads/' . implode('/', $segments);
    $uploadDir = __DIR__ . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $relativeDir);
    if (!is_dir($uploadDir)) {
        mkdir($uploadDir, 0777, true);
    }

    $originalName = trim((string) ($file['name'] ?? ''));
    $safeName = preg_replace('/[^A-Za-z0-9._-]/', '_', basename($originalName));
    $safeName = $safeName !== '' ? $safeName : ($prefix . '_' . time());
    $targetName = $prefix . '_' . time() . '_' . $safeName;
    $targetPath = $uploadDir . DIRECTORY_SEPARATOR . $targetName;

    if (!move_uploaded_file((string) $file['tmp_name'], $targetPath)) {
        return ['path' => '', 'name' => ''];
    }

    return [
        'path' => $relativeDir . '/' . $targetName,
        'name' => $originalName !== '' ? $originalName : $targetName,
    ];
}

if (!isset($_SESSION['user_id']) || strtolower((string) ($_SESSION['role'] ?? '')) !== 'staff') {
    jsonResponse([
        'status' => 'error',
        'message' => 'Unauthorized',
    ], 403);
}

$action = $_GET['action'] ?? $_POST['action'] ?? '';

try {
    ensureSubjectTeachersTable($conn);
    switch ($action) {
        case 'getAllData':
            // All names below map directly to docs/database-v2.sql.
            $membersStmt = $conn->query('
                SELECT 
                    u.user_id as id,
                    u.role,
                    u.account_status as status_account,
                    COALESCE(s.full_name, t.full_name, p.full_name, NULLIF(TRIM(stf.first_name || \' \' || stf.last_name), \'\'), \'-\') as name,
                    COALESCE(s.email, t.email, p.email, \'-\') as email,
                    COALESCE(s.phone, t.phone, p.phone, \'-\') as phone
                FROM public.users u
                LEFT JOIN public.students s ON s.user_id = u.user_id
                LEFT JOIN public.teachers t ON t.user_id = u.user_id
                LEFT JOIN public.parents p ON p.user_id = u.user_id
                LEFT JOIN public.staff stf ON u.user_id = stf.user_id
                ORDER BY u.user_id DESC
            ');
            $curriculaStmt = $conn->query("SELECT curriculum_id AS id, code, name, level, status FROM public.curricula ORDER BY curriculum_id ASC");
            $subjectsStmt = $conn->query("
                SELECT c.course_id AS id, c.code, c.name, c.credits AS credit,
                       COALESCE(STRING_AGG(DISTINCT ct.teacher_id::text, ','), '') AS teacher_ids,
                       COALESCE(STRING_AGG(DISTINCT t.full_name, ', '), 'ยังไม่มีผู้ดูแล') AS teacher_name,
                       COALESCE((SELECT cc.requirement_type FROM public.curriculum_courses cc WHERE cc.course_id = c.course_id ORDER BY cc.curriculum_id LIMIT 1), 'elective') AS type
                FROM public.courses c
                LEFT JOIN public.course_teachers ct ON ct.course_id = c.course_id
                LEFT JOIN public.teachers t ON t.user_id = ct.teacher_id
                GROUP BY c.course_id, c.code, c.name, c.credits
                ORDER BY c.course_id ASC
            ");
            $teachersStmt = $conn->query("SELECT user_id AS id, full_name AS name FROM public.teachers ORDER BY full_name ASC");

            jsonResponse([
                'status' => 'success',
                'members' => fetchAllRows($membersStmt),
                'curricula' => fetchAllRows($curriculaStmt),
                'subjects' => fetchAllRows($subjectsStmt),
                'teachers' => fetchAllRows($teachersStmt)
            ]);
            break;

        case 'createStaff':
            $memberId = preg_replace('/\D+/', '', postValue('user_id'));
            $password = (string) ($_POST['password'] ?? '');
            $firstName = postValue('firstname');
            $lastName = postValue('lastname');

            if (strlen($memberId) !== 13 || $password === '' || $firstName === '' || $lastName === '') {
                jsonResponse(['status' => 'error', 'message' => 'ข้อมูลเจ้าหน้าที่ไม่ครบถ้วน'], 400);
            }

            $conn->beginTransaction();
            $conn->prepare('INSERT INTO public.users (user_id, password_hash, role) VALUES (:id, :password_hash, \'staff\')')
                ->execute([':id' => $memberId, ':password_hash' => password_hash($password, PASSWORD_DEFAULT)]);
            $conn->prepare('INSERT INTO public.staff (user_id, first_name, last_name) VALUES (:id, :first_name, :last_name)')
                ->execute([':id' => $memberId, ':first_name' => $firstName, ':last_name' => $lastName]);
            $conn->commit();
            jsonResponse(['status' => 'success']);
            break;

        case 'saveMember':
            $memberId = postValue('id');
            $firstName = postValue('firstname');
            $lastName = postValue('lastname');
            $email = postValue('email');
            $requestedRole = strtolower(postValue('role'));
            $accountStatus = strtolower(postValue('status', 'active'));

            $roles = ['student' => true, 'teacher' => true, 'parent' => true, 'staff' => true];

            if ($memberId === '' || $firstName === '') {
                jsonResponse(['status' => 'error', 'message' => 'กรุณาระบุรหัสสมาชิกและชื่อ'], 400);
            }
            if (!isset($roles[$requestedRole])) {
                jsonResponse(['status' => 'error', 'message' => 'บทบาทสมาชิกไม่ถูกต้อง'], 400);
            }
            if (!in_array($accountStatus, ['active', 'inactive'], true)) {
                jsonResponse(['status' => 'error', 'message' => 'สถานะบัญชีไม่ถูกต้อง'], 400);
            }
            if ($email !== '' && !filter_var($email, FILTER_VALIDATE_EMAIL)) {
                jsonResponse(['status' => 'error', 'message' => 'รูปแบบอีเมลไม่ถูกต้อง'], 400);
            }

            $userStmt = $conn->prepare('SELECT user_id FROM public.users WHERE user_id = :id FOR UPDATE');
            $conn->beginTransaction();
            $userStmt->execute([':id' => $memberId]);
            if (!$userStmt->fetchColumn()) {
                $conn->rollBack();
                jsonResponse(['status' => 'error', 'message' => 'ไม่พบสมาชิกที่ต้องการแก้ไข'], 404);
            }

            $fullName = trim($firstName . ' ' . $lastName);
            switch ($requestedRole) {
                case 'student':
                    $profile = $conn->prepare('SELECT 1 FROM public.students WHERE user_id = :id');
                    $profile->execute([':id' => $memberId]);
                    if ($profile->fetchColumn()) {
                        $statement = $conn->prepare('UPDATE public.students SET full_name = :name, email = :email, updated_at = NOW() WHERE user_id = :id');
                    } else {
                        $statement = $conn->prepare('INSERT INTO public.students (user_id, full_name, email) VALUES (:id, :name, :email)');
                    }
                    $statement->execute([':id' => $memberId, ':name' => $fullName, ':email' => $email !== '' ? $email : null]);
                    break;

                case 'teacher':
                    $profile = $conn->prepare('SELECT 1 FROM public.teachers WHERE user_id = :id');
                    $profile->execute([':id' => $memberId]);
                    if ($profile->fetchColumn()) {
                        $statement = $conn->prepare('UPDATE public.teachers SET full_name = :name, email = :email, updated_at = NOW() WHERE user_id = :id');
                    } else {
                        $statement = $conn->prepare('INSERT INTO public.teachers (user_id, full_name, email) VALUES (:id, :name, :email)');
                    }
                    $statement->execute([':id' => $memberId, ':name' => $fullName, ':email' => $email !== '' ? $email : null]);
                    break;

                case 'parent':
                    $profile = $conn->prepare('SELECT 1 FROM public.parents WHERE user_id = :id');
                    $profile->execute([':id' => $memberId]);
                    if ($profile->fetchColumn()) {
                        $statement = $conn->prepare('UPDATE public.parents SET full_name = :name, email = :email, updated_at = NOW() WHERE user_id = :id');
                    } else {
                        $statement = $conn->prepare('INSERT INTO public.parents (user_id, full_name, email) VALUES (:id, :name, :email)');
                    }
                    $statement->execute([':id' => $memberId, ':name' => $fullName, ':email' => $email !== '' ? $email : null]);
                    break;

                case 'staff':
                    $profile = $conn->prepare('SELECT 1 FROM public.staff WHERE user_id = :id');
                    $profile->execute([':id' => $memberId]);
                    if ($profile->fetchColumn()) {
                        $statement = $conn->prepare('UPDATE public.staff SET first_name = :firstname, last_name = :lastname, updated_at = NOW() WHERE user_id = :id');
                    } else {
                        $statement = $conn->prepare('INSERT INTO public.staff (user_id, first_name, last_name) VALUES (:id, :firstname, :lastname)');
                    }
                    $statement->execute([':id' => $memberId, ':firstname' => $firstName, ':lastname' => $lastName]);
                    break;
            }

            $statement = $conn->prepare('UPDATE public.users SET role = :role, account_status = :account_status, updated_at = NOW() WHERE user_id = :id');
            $statement->execute([':id' => $memberId, ':role' => $requestedRole, ':account_status' => $accountStatus]);
            $conn->commit();
            jsonResponse(['status' => 'success']);
            break;

        case 'saveSubject':
            $subjectId = $_POST['id'] ?? '';
            $teacherIds = json_decode((string) ($_POST['teacher_ids'] ?? '[]'), true);
            if (!is_array($teacherIds)) { $teacherIds = []; }
            // รองรับคำขอจากหน้าเว็บเวอร์ชันเดิมที่เลือกอาจารย์ได้คนเดียว
            if (!$teacherIds && postValue('teacher_id') !== '') { $teacherIds = [postValue('teacher_id')]; }
            $teacherIds = array_values(array_unique(array_filter(array_map(static fn($id) => trim((string) $id), $teacherIds))));
            if ($teacherIds) {
                $teacherCheck = $conn->prepare('SELECT 1 FROM public.teachers WHERE user_id = :id');
                foreach ($teacherIds as $teacherId) {
                    $teacherCheck->execute([':id' => $teacherId]);
                    if (!$teacherCheck->fetchColumn()) {
                        jsonResponse(['status' => 'error', 'message' => 'พบอาจารย์ที่เลือกไม่อยู่ในระบบ'], 400);
                    }
                }
            }
            $primaryTeacherId = $teacherIds[0] ?? null;

            $params = [':code' => postValue('code'), ':name' => postValue('name'), ':credit' => (int) postValue('credit', '0')];

            if (!empty($subjectId)) {
                $params[':id'] = $subjectId;
                $statement = $conn->prepare("
                    UPDATE public.courses SET code = :code, name = :name, credits = :credit, updated_at = NOW() WHERE course_id = :id
                ");
            } else {
                $params[':created_by'] = (string) $_SESSION['user_id'];
                $statement = $conn->prepare("
                    INSERT INTO public.courses (code, name, credits, created_by) VALUES (:code, :name, :credit, :created_by) RETURNING course_id
                ");
            }
            $conn->beginTransaction();
            $statement->execute($params);
            $savedSubjectId = !empty($subjectId) ? $subjectId : (string) $statement->fetchColumn();
            $conn->prepare('DELETE FROM public.course_teachers WHERE course_id = :course_id')->execute([':course_id' => $savedSubjectId]);
            if ($teacherIds) {
                $assignment = $conn->prepare('INSERT INTO public.course_teachers (course_id, teacher_id) VALUES (:course_id, :teacher_id)');
                foreach ($teacherIds as $teacherId) {
                    $assignment->execute([':course_id' => $savedSubjectId, ':teacher_id' => $teacherId]);
                }
            }
            $conn->commit();
            jsonResponse(['status' => 'success']);
            break;

        case 'deleteSubject':
            $subjectId = $_POST['id'] ?? '';
            $statement = $conn->prepare("DELETE FROM public.courses WHERE course_id = :id");
            $statement->execute([':id' => $subjectId]);
            jsonResponse(['status' => 'success']);
            break;

        case 'getCurriculumSubjects':
            $curriculumId = $_GET['curriculum_id'] ?? '';
            if (empty($curriculumId)) { jsonResponse(['status' => 'error', 'message' => 'Missing ID'], 400); }
            $allSubjectsStmt = $conn->query("SELECT course_id AS id, code, name FROM public.courses ORDER BY course_id ASC");
            $selectedStmt = $conn->prepare("SELECT course_id FROM public.curriculum_courses WHERE curriculum_id = :id");
            $selectedStmt->execute([':id' => $curriculumId]);
            jsonResponse([
                'status' => 'success',
                'subjects' => fetchAllRows($allSubjectsStmt),
                'selected' => $selectedStmt->fetchAll(PDO::FETCH_COLUMN) ?: []
            ]);
            break;

        case 'saveCurriculumSubjects':
            $curriculumId = $_POST['curriculum_id'] ?? '';
            $subjectIds = isset($_POST['subjects']) ? json_decode($_POST['subjects'], true) : [];
            if (empty($curriculumId)) { jsonResponse(['status' => 'error', 'message' => 'Missing ID'], 400); }
            $conn->beginTransaction();
            try {
                $delStmt = $conn->prepare("DELETE FROM public.curriculum_courses WHERE curriculum_id = :id");
                $delStmt->execute([':id' => $curriculumId]);
                if (!empty($subjectIds) && is_array($subjectIds)) {
                    $insertStmt = $conn->prepare("INSERT INTO public.curriculum_courses (curriculum_id, course_id) VALUES (:cid, :sid)");
                    foreach ($subjectIds as $sid) { $insertStmt->execute([':cid' => $curriculumId, ':sid' => $sid]); }
                }
                $conn->commit();
                jsonResponse(['status' => 'success']);
            } catch (Exception $e) { $conn->rollBack(); throw $e; }
            break;

        case 'saveCurriculum':
            $curriculumId = $_POST['id'] ?? '';
            $code = strtoupper(postValue('code'));
            $name = postValue('name');
            $status = postValue('status', 'active');
            if ($status === 'inactive') { $status = 'archived'; }
            if ($code === '' || $name === '') { jsonResponse(['status' => 'error', 'message' => 'กรุณากรอกรหัสและชื่อหลักสูตร'], 400); }
            if (!in_array($status, ['draft', 'active', 'archived'], true)) { jsonResponse(['status' => 'error', 'message' => 'สถานะหลักสูตรไม่ถูกต้อง'], 400); }
            $duplicate = $conn->prepare('SELECT 1 FROM public.curricula WHERE code = :code AND curriculum_id <> COALESCE(NULLIF(:id, \'\')::bigint, 0)');
            $duplicate->execute([':code' => $code, ':id' => (string) $curriculumId]);
            if ($duplicate->fetchColumn()) { jsonResponse(['status' => 'error', 'message' => 'รหัสหลักสูตรนี้มีอยู่แล้ว กรุณาใช้รหัสอื่น หรือเลือกแก้ไขหลักสูตรเดิม'], 409); }
            $params = [':code' => $code, ':name' => $name, ':level' => postValue('level', 'ม.ปลาย'), ':status' => $status];
            if (!empty($curriculumId)) {
                $params[':id'] = $curriculumId;
                $statement = $conn->prepare("UPDATE public.curricula SET code = :code, name = :name, level = :level, status = :status, updated_at = NOW() WHERE curriculum_id = :id");
            } else {
                $statement = $conn->prepare("INSERT INTO public.curricula (code, name, level, status) VALUES (:code, :name, :level, :status)");
            }
            $statement->execute($params);
            jsonResponse(['status' => 'success']);
            break;

        case 'deleteCurriculum':
            $curriculumId = $_POST['id'] ?? '';
            $statement = $conn->prepare("DELETE FROM public.curricula WHERE curriculum_id = :id");
            $statement->execute([':id' => $curriculumId]);
            jsonResponse(['status' => 'success']);
            break;

        case 'getLessons':
            $subjectId = $_GET['subject_id'] ?? '';
            if (empty($subjectId)) { jsonResponse(['status' => 'error', 'message' => 'Missing ID'], 400); }
            $lessonStmt = $conn->prepare("
                SELECT
                    l.lesson_id AS id, l.title, l.content,
                    COALESCE(d.url, '') AS document_path, COALESCE(d.title, '') AS document_name
                FROM public.lessons
                l LEFT JOIN LATERAL (
                    SELECT title, url FROM public.lesson_resources
                    WHERE lesson_id = l.lesson_id AND resource_type = 'document' ORDER BY position LIMIT 1
                ) d ON true
                WHERE l.course_id = :subject_id
                ORDER BY l.position ASC
                LIMIT 3
            ");
            $lessonStmt->execute([':subject_id' => $subjectId]);
            jsonResponse(['status' => 'success', 'lessons' => fetchAllRows($lessonStmt)]);
            break;

        case 'getSubjectEditorData':
            $subjectId = $_GET['subject_id'] ?? '';
            if (empty($subjectId)) { jsonResponse(['status' => 'error', 'message' => 'Missing ID'], 400); }
            $subjectStmt = $conn->prepare("
                SELECT
                    course_id AS id, code, name, credits AS credit, 'elective' AS type
                FROM public.courses
                WHERE course_id = :id
                LIMIT 1
            ");
            $subjectStmt->execute([':id' => $subjectId]);
            $subject = $subjectStmt->fetch(PDO::FETCH_ASSOC);
            if (!$subject) {
                jsonResponse(['status' => 'error', 'message' => 'Subject not found'], 404);
            }

            $lessonStmt = $conn->prepare("
                SELECT
                    l.lesson_id AS id, l.title, l.content,
                    COALESCE(d.url, '') AS document_path, COALESCE(d.title, '') AS document_name
                FROM public.lessons l LEFT JOIN LATERAL (
                    SELECT title, url FROM public.lesson_resources WHERE lesson_id = l.lesson_id AND resource_type = 'document' ORDER BY position LIMIT 1
                ) d ON true
                WHERE l.course_id = :subject_id
                ORDER BY l.position ASC
                LIMIT 3
            ");
            $lessonStmt->execute([':subject_id' => $subjectId]);

            jsonResponse([
                'status' => 'success',
                'subject' => $subject,
                'lessons' => fetchAllRows($lessonStmt),
            ]);
            break;

        case 'saveLesson':
            $lessonId = $_POST['id'] ?? '';
            $subjectId = $_POST['subject_id'] ?? '';
            if (empty($subjectId)) { jsonResponse(['status' => 'error', 'message' => 'Missing ID'], 400); }
            $isNewLesson = trim((string) $lessonId) === '';
            if ($isNewLesson && countSubjectLessons($conn, $subjectId) >= MAX_LESSONS_PER_SUBJECT) {
                jsonResponse(['status' => 'error', 'message' => 'รายวิชานี้มีบทเรียนครบ 3 บทแล้ว'], 400);
            }
            $params = [':course_id' => $subjectId, ':title' => postValue('title'), ':content' => postValue('content')];
            if ($isNewLesson) {
                $statement = $conn->prepare('INSERT INTO public.lessons (course_id, title, content, position) VALUES (:course_id, :title, :content, (SELECT COALESCE(MAX(position), 0) + 1 FROM public.lessons WHERE course_id = :course_id))');
            } else {
                $params[':id'] = $lessonId;
                $statement = $conn->prepare('UPDATE public.lessons SET title = :title, content = :content, updated_at = NOW() WHERE lesson_id = :id AND course_id = :course_id');
            }
            $statement->execute($params);
            jsonResponse(['status' => 'success']);
            break;

        case 'deleteLesson':
            $lessonId = $_POST['id'] ?? '';
            $subjectId = $_POST['subject_id'] ?? '';
            $statement = $conn->prepare("DELETE FROM public.lessons WHERE lesson_id = :id AND course_id = :subject_id");
            $statement->execute([':id' => $lessonId, ':subject_id' => $subjectId]);
            jsonResponse(['status' => 'success']);
            break;

        case 'getVideoEditorData':
            $subjectId = trim((string) ($_GET['subject_id'] ?? ''));
            if ($subjectId === '') { jsonResponse(['status' => 'error', 'message' => 'Missing subject ID'], 400); }

            $subjectStmt = $conn->prepare("SELECT course_id AS id, name FROM public.courses WHERE course_id = :id LIMIT 1");
            $subjectStmt->execute([':id' => $subjectId]);
            $subject = $subjectStmt->fetch(PDO::FETCH_ASSOC);
            if (!$subject) { jsonResponse(['status' => 'error', 'message' => 'ไม่พบรายวิชานี้'], 404); }

            $lessonStmt = $conn->prepare("SELECT lesson_id AS id, title FROM public.lessons WHERE course_id = :subject_id ORDER BY position ASC LIMIT 3");
            $lessonStmt->execute([':subject_id' => $subjectId]);

            $videoStmt = $conn->prepare("
                SELECT
                    r.resource_id AS id, r.title, r.url, '' AS description, r.duration_seconds,
                    r.position AS display_order, r.lesson_id AS lessons_id, l.title AS lesson_title
                FROM public.lesson_resources r
                INNER JOIN public.lessons l ON l.lesson_id = r.lesson_id
                WHERE l.course_id = :subject_id AND r.resource_type = 'video'
                ORDER BY r.position ASC, r.resource_id ASC
            ");
            $videoStmt->execute([':subject_id' => $subjectId]);

            jsonResponse([
                'status' => 'success',
                'subject' => $subject,
                'lessons' => fetchAllRows($lessonStmt),
                'videos' => fetchAllRows($videoStmt),
            ]);
            break;

        case 'saveVideo':
            $subjectId = postValue('subject_id');
            $videoId = trim((string) ($_POST['id'] ?? ''));
            $title = postValue('title');
            if ($subjectId === '' || $title === '') { jsonResponse(['status' => 'error', 'message' => 'กรุณาระบุวิชาและชื่อวิดีโอ'], 400); }

            $currentUrl = '';
            if ($videoId !== '') {
                $currentStmt = $conn->prepare("SELECT r.url FROM public.lesson_resources r INNER JOIN public.lessons l ON l.lesson_id = r.lesson_id WHERE r.resource_id = :id AND l.course_id = :subject_id AND r.resource_type = 'video' LIMIT 1");
                $currentStmt->execute([':id' => $videoId, ':subject_id' => $subjectId]);
                $currentUrl = (string) ($currentStmt->fetchColumn() ?: '');
                if ($currentUrl === '') { jsonResponse(['status' => 'error', 'message' => 'ไม่พบวิดีโอที่ต้องการแก้ไข'], 404); }
            }

            $upload = uploadLessonFile('video_file', ['courses', sanitizePathSegment($subjectId), 'videos'], 'video');
            $videoUrl = postValue('url');
            if ($upload['path'] !== '') {
                $videoUrl = $upload['path'];
            } elseif ($videoUrl === '') {
                $videoUrl = $currentUrl;
            }
            if ($videoUrl === '') { jsonResponse(['status' => 'error', 'message' => 'กรุณาอัปโหลดไฟล์วิดีโอหรือระบุลิงก์วิดีโอ'], 400); }

            $lessonId = postValue('lesson_id');
            if ($lessonId !== '') {
                $lessonStmt = $conn->prepare("SELECT 1 FROM public.lessons WHERE lesson_id = :lesson_id AND course_id = :subject_id");
                $lessonStmt->execute([':lesson_id' => $lessonId, ':subject_id' => $subjectId]);
                if (!$lessonStmt->fetchColumn()) { jsonResponse(['status' => 'error', 'message' => 'บทเรียนที่เลือกไม่ได้อยู่ในรายวิชานี้'], 400); }
            }

            $params = [
                ':title' => $title,
                ':url' => $videoUrl,
                ':duration' => postValue('duration') !== '' ? (int) postValue('duration') : null,
                ':display_order' => max(1, (int) (postValue('display_order', '1') ?: 1)),
                ':lesson_id' => $lessonId !== '' ? $lessonId : null,
            ];
            if ($videoId === '') {
                if ($lessonId === '') { jsonResponse(['status' => 'error', 'message' => 'กรุณาเลือกบทเรียนสำหรับวิดีโอ'], 400); }
                $statement = $conn->prepare("INSERT INTO public.lesson_resources (lesson_id, resource_type, title, url, duration_seconds, position) VALUES (:lesson_id, 'video', :title, :url, :duration, :display_order)");
            } else {
                $params[':id'] = $videoId;
                $statement = $conn->prepare("UPDATE public.lesson_resources SET title = :title, url = :url, duration_seconds = :duration, position = :display_order, lesson_id = :lesson_id WHERE resource_id = :id AND resource_type = 'video'");
            }
            $statement->execute($params);
            jsonResponse(['status' => 'success']);
            break;

        case 'deleteVideo':
            $videoId = trim((string) ($_POST['id'] ?? ''));
            $subjectId = postValue('subject_id');
            if ($videoId === '' || $subjectId === '') { jsonResponse(['status' => 'error', 'message' => 'Missing video ID'], 400); }
            $statement = $conn->prepare("DELETE FROM public.lesson_resources r USING public.lessons l WHERE r.lesson_id = l.lesson_id AND r.resource_id = :id AND l.course_id = :subject_id AND r.resource_type = 'video'");
            $statement->execute([':id' => $videoId, ':subject_id' => $subjectId]);
            jsonResponse(['status' => 'success']);
            break;

        case 'deleteMember':
            $memberId = $_POST['id'] ?? '';
            if (empty($memberId)) { jsonResponse(['status' => 'error', 'message' => 'Missing ID'], 400); }
            // The foreign key removes the matching staff profile automatically.
            $statement = $conn->prepare('DELETE FROM public.users WHERE user_id = :id');
            $statement->execute([':id' => $memberId]);
            jsonResponse(['status' => 'success']);
            break;

        default:
            jsonResponse(['status' => 'error', 'message' => 'Invalid action'], 400);
    }
} catch (Throwable $exception) {
    if ($conn->inTransaction()) { $conn->rollBack(); }
    jsonResponse(['status' => 'error', 'message' => 'DB Error: ' . $exception->getMessage()], 500);
}
