<?php
session_start();
if (!isset($_SESSION['user_id']) || ($_SESSION['role'] ?? '') !== 'teacher') { header('Location: login.php'); exit; }
$subjectId = trim((string) ($_GET['subject_id'] ?? ''));
?>
<!DOCTYPE html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>คลังวิดีโอของอาจารย์</title><link rel="stylesheet" href="staff_subject_editor.css"><link rel="stylesheet" href="theme.css"></head>
<body><div class="bg-grid"></div><div class="glow-orb orb-1"></div><div class="glow-orb orb-2"></div><header class="topbar"><a class="btn-ghost" href="teacherdash.php?subject_id=<?= htmlspecialchars($subjectId, ENT_QUOTES, 'UTF-8') ?>">← กลับแดชบอร์ดอาจารย์</a><div class="topbar-copy"><span class="eyebrow">TEACHER VIDEO LIBRARY</span><h1>จัดการวิดีโอรายวิชา</h1></div></header>
<main class="page-shell"><section class="hero-card"><div><p class="hero-label">Subject videos</p><h2 id="subjectTitle">กำลังโหลดรายวิชา...</h2><p class="hero-sub">อัปโหลดไฟล์วิดีโอได้เฉพาะรายวิชาที่คุณรับผิดชอบ</p></div><div class="hero-meta" id="videoMeta"></div></section>
<section class="panel lessons-panel"><div class="panel-head lesson-head"><div><p class="panel-label">Videos</p><h3>คลังวิดีโอ</h3></div><button type="button" id="addVideoBtn" class="btn-primary">+ เพิ่มวิดีโอ</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ชื่อวิดีโอ</th><th>บทเรียน</th><th>จัดการ</th></tr></thead><tbody id="videoTableBody"></tbody></table></div></section>
<section class="panel" id="videoEditor"><div class="panel-head"><div><p class="panel-label">Video form</p><h3 id="videoFormTitle">เพิ่มวิดีโอใหม่</h3></div></div><form id="videoForm" class="form-card" enctype="multipart/form-data"><input type="hidden" id="videoId"><div class="form-grid-2"><div class="form-field"><label class="form-label">ชื่อวิดีโอ *</label><div class="input-wrap"><input id="videoTitle" required></div></div><div class="form-field"><label class="form-label">บทเรียนที่เกี่ยวข้อง</label><div class="input-wrap select-wrap"><select id="videoLesson"><option value="">วิดีโอรวมของรายวิชา</option></select></div></div></div><div class="form-field"><label class="form-label">คำอธิบาย</label><div class="input-wrap"><textarea id="videoDescription" rows="3"></textarea></div></div><div class="resource-card"><div class="resource-head"><div class="resource-icon video">🎬</div><div><h4>ไฟล์วิดีโอ *</h4><p>เลือกไฟล์วิดีโอเพื่ออัปโหลดและบันทึก</p></div></div><div class="input-wrap file-wrap"><input id="videoFile" type="file" accept="video/*" required></div></div><div class="form-actions"><button type="button" class="btn-ghost" id="clearVideoBtn">ล้างฟอร์ม</button><button class="btn-primary">บันทึกวิดีโอ</button></div></form></section><section id="errorPanel" class="panel error-panel" hidden><div id="errorMessage" class="error-body"></div></section></main><div id="toast" class="toast"></div><script>window.TEACHER_SUBJECT_ID=<?= json_encode($subjectId, JSON_UNESCAPED_UNICODE) ?>;</script><script src="teacher_video_editor.js"></script></body></html>
