(() => {
  const subjectId = String(window.TEACHER_SUBJECT_ID || '').trim(), $ = (id) => document.getElementById(id);
  let lessons = [], videos = [];
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast = (m, t='success') => { const e=$('toast'); e.textContent=m; e.className=`toast show ${t}`; clearTimeout(toast.i); toast.i=setTimeout(()=>e.classList.remove('show'),3000); };
  const request = async (form) => { const r=await fetch('teacher_api.php',{method:'POST',body:form}); const d=await r.json(); if(!d.success) throw new Error(d.message || 'ทำรายการไม่สำเร็จ'); return d; };
  function reset() { $('videoForm').reset(); $('videoId').value=''; $('videoFormTitle').textContent='เพิ่มวิดีโอใหม่'; }
  function render(data) { lessons=data.lessons||[]; videos=data.videos||[]; $('subjectTitle').textContent=`วิดีโอของวิชา ${subjectId}`; $('videoMeta').innerHTML=`<span class="meta-pill">วิดีโอ ${videos.length} รายการ</span>`; $('videoLesson').innerHTML='<option value="">วิดีโอรวมของรายวิชา</option>'+lessons.map(l=>`<option value="${esc(l.id)}">${esc(l.title)}</option>`).join(''); $('videoTableBody').innerHTML=videos.length?videos.map(v=>`<tr><td>${esc(v.title)}</td><td>${esc(v.lesson_title||'วิดีโอรวมของรายวิชา')}</td><td><div class="action-btns"><button class="btn-icon" data-edit="${esc(v.id)}">✎</button><button class="btn-icon danger" data-delete="${esc(v.id)}">✖</button></div></td></tr>`).join(''):'<tr><td colspan="3" class="empty-cell">ยังไม่มีวิดีโอในวิชานี้</td></tr>'; }
  async function load() { if(!subjectId) { $('errorPanel').hidden=false; $('errorMessage').textContent='ไม่พบรหัสวิชา'; return; } const f=new FormData(); f.append('action','get_videos'); f.append('subject_id',subjectId); try { render(await request(f)); } catch(e) { $('errorPanel').hidden=false; $('errorMessage').textContent=e.message; } }
  function edit(id) { const v=videos.find(x=>String(x.id)===String(id)); if(!v)return; $('videoId').value=v.id; $('videoTitle').value=v.title||''; $('videoDescription').value=v.description||''; $('videoLesson').value=v.lessons_id||''; $('videoFormTitle').textContent=`แก้ไขวิดีโอ: ${v.title}`; $('videoEditor').scrollIntoView({behavior:'smooth'}); }
  $('videoForm').addEventListener('submit',async e=>{e.preventDefault();const file=$('videoFile').files[0];if(!file){toast('กรุณาเลือกไฟล์วิดีโอ','error');return;}const f=new FormData();f.append('action','save_video');f.append('subject_id',subjectId);f.append('video_id',$('videoId').value);f.append('title',$('videoTitle').value.trim());f.append('description',$('videoDescription').value.trim());f.append('lesson_id',$('videoLesson').value);f.append('video_file',file);try{await request(f);toast('บันทึกวิดีโอเรียบร้อยแล้ว');reset();load();}catch(x){toast(x.message,'error');}});
  $('addVideoBtn').onclick=()=>{$('videoEditor').scrollIntoView({behavior:'smooth'});reset();}; $('clearVideoBtn').onclick=reset;
  $('videoTableBody').onclick=async e=>{const editBtn=e.target.closest('[data-edit]'), delBtn=e.target.closest('[data-delete]');if(editBtn)return edit(editBtn.dataset.edit);if(!delBtn||!confirm('ยืนยันการลบวิดีโอนี้?'))return;const f=new FormData();f.append('action','delete_video');f.append('subject_id',subjectId);f.append('video_id',delBtn.dataset.delete);try{await request(f);toast('ลบวิดีโอแล้ว');load();}catch(x){toast(x.message,'error');}};
  load();
})();
